version: '3.3'


services:
    django:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: tenant_django:base
        command: ./getBici/manage.py runserver 0.0.0.0:8000
        ports:
          - 8000:8000
        volumes:
          - ./:/opt/core/
        stdin_open: true
        tty: true
        depends_on:
          - postgres

    postgres:
        image: postgres:12-alpine
        env_file:
          - dev.env
        ports:
          - 5432:5432
        volumes:
          - ./database:/var/lib/postgresql/data
